### ISSUE TITLE
With default usage example, it does not parse `///` comments.

### ISSUE THREAD

**Issue by dherges** [SassDoc/scss-comment-parser#31]
Using the [default usage](https://github.com/SassDoc/scss-comment-parser#usage) example plus adding a custom annotation, like:

```js
const parser = new ScssCommentParser({
  _: {
    alias: {
      'aliasTest': 'annotationTest'
    }
  },
  color: function () {

    return {
      name: 'color',

      parse: function (text) {
        return text.trim()
      }
    }
  },
  annotationTest: function ( commentLine ) {
    return 'Working';
  }
});
```

Now, triple-slash comments are not parsed. Input:

```scss
/// My best color in town
/// @color
$my-color: #f00;
```

---

Block comments, however, are parsed:

```scss
/**
 * My best color in town
 * @color
 */
$my-color: #ff0000;
```

Output:

```json
    "variable": [
      {
        "description": "My best color in town\n",
        "context": {
          "type": "variable",
          "name": "my-color",
          "value": "#ff0000",
          "scope": "private"
        },
        "color": [
          {
            "name": "color"
          }
        ]
      }
```

Is this intended behaviour? What am I doing wrong?

**Comment by pascalduez** [comment]
Hey,

Humm weird, that should be the contrary...
We will try to reproduce.

Care to provide a sample repo/codesandbox/whatever reproducing the issue?

**Comment by dherges** [comment]
Oh no guys...

https://www.npmjs.com/package/scss-comment-parser

https://www.npmjs.com/package/scsscommentparser

Guess what? Yes! 🚀

**Comment by pascalduez** [comment]
Oh noes, WTF... 

Sorry for the loss of your time @dherges. And thanks for the PR!

**Comment by dherges** [comment]
@pascalduez no worries! you don't have to excuse. I don't see it as a loss!
