### ISSUE TITLE
Semicolon inside variable content breaks parser.

### ISSUE THREAD

**Issue by jgerigmeyer** [SassDoc/scss-comment-parser#37]
This is really just re-opening #15 (and by extension https://github.com/SassDoc/sassdoc/issues/191). When it was initially fixed (https://github.com/SassDoc/scss-comment-parser/commit/8e5f8d24214b9313ecc0ab7ca689dcbcc5f384bf) no test case was added, so when it was broken again (https://github.com/SassDoc/scss-comment-parser/commit/2fdc1db528302453e830e1e9f23000b2fccefbf9) it went unnoticed.

The original fix did cause a regression parsing line comments after the trailing semicolon (https://github.com/SassDoc/scss-comment-parser/issues/17), but the "fix" for that was really just to unintentionally re-introduce #15 in an incorrect merge conflict resolution (https://github.com/SassDoc/scss-comment-parser/commit/2fdc1db528302453e830e1e9f23000b2fccefbf9).

So, here we are again. I've started by adding a (failing) test case for #15 in #36. I'll dig into the regex a bit and see if I can figure out a fix.

**Comment by jgerigmeyer** [comment]
PR with fix (and passing test) submitted: #36.

**Comment by pascalduez** [comment]
Thanks a bunch @jgerigmeyer for the archeology work and the PR! 
Fixed as of `scss-comment-parser@0.8.4`.
